# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 01:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('natural_tree', '0002_auto_20160120_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='natural_tree.Collection'),
        ),
    ]
