# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('natural_tree', '0004_relatedobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='collection',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='natural_tree.Collection'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='natural_tree.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='natural_tree.Role', to='natural_tree.Collection'),
        ),
        migrations.AlterIndexTogether(
            name='role',
            index_together=set([('user', 'type'), ('collection', 'type')]),
        ),
    ]
