# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_tree', '0002_relatedobject'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='node',
            index_together=set([('kind', 'kind_id')]),
        ),
    ]
